### ISSUE TITLE
Issue checklist

### ISSUE THREAD

**Issue by glitch-in-the-herring** [glitch-in-the-herring/bof4-text-extractor#3]
Some issues found

- [x] Space is not printed (`0x20`  should be treated as a space)
- [x] Numbers are not printed 
- [ ] Some symbols are not printed
